### ISSUE TITLE
@media queries

### ISSUE THREAD

**Issue by csiszi** [niftylettuce/email-templates#135] opened 2015-07-26 10:41 UTC
Hi all,

I'm new to the node world and currently experimenting with email-templates. AFAIK, juice2 supports media queries. What's the best practice for using them in email-templates? Split the css into 2 parts, include the media queries in the html.\* and put everything else to the style._? I can't put them into style._, since they're not included in the rendered html, but they have to be there in order to work.

Thanks!

**Comment by jeduan** [comment] 2015-07-27 07:17
Hi @csiszi!

You can check out the juiceOptions parameter, which has a way to tell juice not to remove the media queries.

You can pass them like here:
https://github.com/niftylettuce/node-email-templates#template-engine-options

And here's the complete list of options:
https://github.com/automattic/juice#options

In particular there's `preserveMediaQueries` and `removeStyleTags`. If this worked please do let me know to close this issue.

**Comment by csiszi** [comment] 2015-07-27 08:03
Hi @jeduan ,

thanks for the answer! I've tried `preserveMediaQueries`, but it's not working in this case (or I'm doing something wrong). node-email-templates is using `juice.inlineContent`, which takes a html (\*.html.\* in this case) and a css (\*.style.\*), and returns the inlined html. It's working, but it doesn't _add_ MQs (or anything else) to the `<head>` section, just returns the inlined html. From juice doc: 

    It does not look at <style> or <link rel="stylesheet"> elements at all.

Maybe I'm missing something, but I couldn't find a way to actually add contents (the whole css or just the MQ's or any other part) to the rendered html from the \*.style.\*. MQs are just the most common parts that need to be included (and not inlined), but you can actually use pseudo selectors in emails (in gmail too!), and since they can't be inlined, they have to live in the `<head>` too.

**Comment by dantman** [comment] 2015-10-22 05:52
Sounds like `juice.inlineContent` is a bit too limited. Perhaps we need an option to make `email-templates` use `juice.juiceResources` instead of `style.*` files. Then `link` tags can be used to import css.

Though style transformation from less, etc... will need a separate flow.

However IMHO that might not be a totally bad thing. This file extension based transformation doesn't lend itself well to using other transforms like postcss and autoprefixer anyways.

**Comment by dantman** [comment] 2015-10-22 10:27
It requires a bit of acrobatics when you're using gulp (to order separate tasks to transform .less files and to build the EmailTemplate). But I can confirm that using `juiceResources` instead of `inlineContent` and importing styles via `<link>` instead of `style.*` works better.

**Comment by custa1200** [comment] 2016-01-10 10:21
I am also running into this issue. Have you got an example of the method you are suggesting. I have gulp watching all my Stylus/PostCSS content so there should always be a rendered CSS file that is created that I could consume. This seems to be a big issue in a world where responsive emails are so important and need media queries. For the record I am using Zurb Ink for mine.

**Comment by custa1200** [comment] 2016-02-04 07:14
@jeduan great to see some updates on this project. I think this for me is my biggest issue with it killing responsive emails, which are pretty much a necessary feature of emails with mobile. Any thoughts around this from what @dantman suggested?

**Comment by row1** [comment] 2016-05-04 09:48
If you are using Handlebars (or another templating language) then you can have a separate css file for your media queries and then use the Handlebars partial to inject the contents of the css file into your main page.

**Comment by niftylettuce** [comment] 2017-10-06 03:22
v3.x is released, see <https://github.com/niftylettuce/email-templates#automatic-inline-css-via-stylesheets>

**Closed by niftylettuce** 2017-10-06 03:22 UTC
Labels: 2.x
