### ISSUE TITLE
Cannot set property 'filename' of null

### ISSUE THREAD

**Issue by Niteesh** [niftylettuce/email-templates#160] opened 2016-03-03 04:20 UTC
I am getting following error while trying to use jade template engine. Can you please help?   

var newsletter = new EmailTemplate(templateDir);
   console.log(newsletter);
   return newsletter.render();

 emailTemplate.render(user, function(error, result){
      console.log(error);
      console.log(result);
    });

TypeError: Cannot set property 'filename' of null
    at /Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/email-templates/lib/template-manager.js:50:21
    at Promise._execute (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/debuggability.js:180:9)
    at Promise._resolveFromExecutor (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:460:18)
    at new Promise (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:76:14)
    at render (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/email-templates/lib/template-manager.js:45:10)
    at renderFile (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/email-templates/lib/util.js:53:38)
    at /Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/email-templates/lib/email-template.js:123:61
    at tryCatcher (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:502:17)
    at Promise._settlePromise (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/Users/XXXXXXXX/Documents/projects/XXXXXXXX/node_modules/bluebird/js/release/promise.js:416:57)

**Comment by row1** [comment] 2016-05-04 10:25
Duplicate of #142 ?

**Comment by niftylettuce** [comment] 2017-10-06 03:23
v3.x released

**Closed by niftylettuce** 2017-10-06 03:23 UTC
Labels: 2.x
