### ISSUE TITLE
Memory leak affecting tests

### ISSUE THREAD

**Issue by Poupouch** [niftylettuce/email-templates#279] opened 2018-02-02 18:38 UTC
Hi guys, we are using `email-templates` v3.3.3 to render only email templates. It seems that the lib is leaking memory somehow. Using `yarn` v1.3.2, `node` v9.4.0, `jest` v22.1.4

```
// ./my.test.js
const Email = require('email-templates');
it('example test', () => {});
```

Run
> yarn jest --runInBand --logHeapUsage --watch my.test.js

Each time the tests are run, it will show a jump of heap usage. Any idea?

**Comment by niftylettuce** [comment] 2018-02-02 23:07
Can you trace the memory leak anymore to determine where it's actually coming from?

<https://www.alexkras.com/simple-guide-to-finding-a-javascript-memory-leak-in-node-js/#find-problem>

**Comment by ramondeklein** [comment] 2018-03-03 19:01
I encountered the same issue and wrote a small application that illustrates the problem. This sample program, including an extensive description, can be found at https://github.com/ramondeklein/pug-email-templates-memleak.

It seems that is caused by a bug (???) in the PUG library. It seems that every time that a PUG template is compiled, it will never be released anymore. I also filed an issue (pugjs/pug#2972) with the pugjs team.

**Comment by niftylettuce** [comment] 2018-03-03 19:48
Thank you @ramondeklein, I've subscribed to those issues you linked and hopefully the pugjs team can help discover the underlying issue.  Especially thanks for your details too in that reproduction repo.

**Comment by ramondeklein** [comment] 2018-03-03 20:20
I fixed it by using pug/juice directly and caching the pug template function. I only use a few templates, so keeping the functions in memory is not an issue to me.

**Comment by niftylettuce** [comment] 2018-03-03 20:26
@ramondeklein if you want to write a patch for `email-templates` here and submit a pull request for this we could have a temporary workaround till that's resolved?

**Comment by niftylettuce** [comment] 2018-05-19 21:30
Closing for now - seems like it is both an issue with core Node and also limited to use with the Debugger opened.  Let me know otherwise.

**Closed by niftylettuce** 2018-05-19 21:30 UTC
