### ISSUE TITLE
What is "transport" exactly?

### ISSUE THREAD

**Issue by nicolasxu** [niftylettuce/email-templates#295] opened 2018-04-14 16:29 UTC
Where do I find document about the transport thing?

**Comment by niftylettuce** [comment] 2018-04-14 18:37
This is a duplicate of #296, but see [this section](https://github.com/niftylettuce/email-templates#basic) in the docs.  Transport is a configuration for sending email (e.g. SMTP configuration username and password).  For full reference see <https://nodemailer.com/transports/>.

**Closed by niftylettuce** 2018-04-14 18:37 UTC
