### ISSUE TITLE
Templates not being accessed?

### ISSUE THREAD

**Issue by Yakitrak** [niftylettuce/email-templates#287] opened 2018-03-13 10:38 UTC
I'm using this library but when I see the email preview, it only it shows "from", "to", "messageid" and "date". It doesn't have a subject and body like your preview example. It also doesn't send when I change the send property to true.

I think the template isn't being acquired properly so I did a 'console.log(email.getTemplatePath());' but it shows 'TypeError: Path must be a string. Received undefined'. I'm not sure why thats happening as my structure is:

```
.
├── helpers
  ├── email.js
  └── emails
    └── signup_consumer
        ├── html.pug
        └── subject.pug
```
my code is:

```
const email = new Email({
    message: {
        from: 'email@mail.com' 
    },
    send: true,
    transport: {
        jsonTransport: true
    }
});
```

```
    email
        .send({
            template: 'signup_consumer',
            message: {
                to: user.email
            },
            locals: {
                name: 'exampleuser',
                sitelink: 'example.com',
            }
        })
        .then(console.log)
        .catch(console.error);
    //console.log(email.getTemplatePath());
```

**Comment by niftylettuce** [comment] 2018-03-13 12:45
@Yakitrak how did you resolve?

**Comment by Yakitrak** [comment] 2018-03-13 12:50
It was looking for the path on 'root/emails' instead of in 'root/helpers/emails'. I changed the path manually on email.config.views.root: 

```
const email = new Email({
    message: {
        from: 'example@example.com'
    },
    views: {
        root: path.join(__dirname, 'emails')
    },
}
```
My mistake, I thought it would look from current directory not from root. Feel free to remove this issue.

**Comment by niftylettuce** [comment] 2018-03-13 12:51
Ah yes this is related to #275

**Comment by niftylettuce** [comment] 2018-05-19 21:29
This is now fixed in v3.6.2 🎉 - please install via `npm install email-templates@latest` or `yarn add email-templates@latest`.  It by default uses `pkg-dir` (see <https://github.com/sindresorhus/pkg-dir>) to get the root directory of the project, and then uses `path.join(root, 'emails')` to get the path to the emails directory in the root folder.

**Closed** 2018-05-19 21:28 UTC

**Comment by Dinuz** [comment] 2018-05-20 05:06
@niftylettuce check my comment on the pkg-dir commit. This solution breaks and fall apart on serveless architecture.

**Comment by niftylettuce** [comment] 2018-05-20 16:37
I had to unpublish v3.6.2 due to this breaking issue with serverless apps <https://github.com/niftylettuce/email-templates/commit/bd499e361aab22125e67cdb15ee58f24e2a7265d#commitcomment-29050761.  I've re-published this in v4.0.0.

**Comment by niftylettuce** [comment] 2018-05-20 16:37
Thanks again @Dinuz

**Comment by Dinuz** [comment] 2018-05-20 17:37
@niftylettuce if we add in the readme that in order to use the old behavior it's necessary explicitly declare under views  root: path.resolve('emails'); I do think we are ok.

e.g. 
```
views: {
      root: path.resolve('emails'),
      options: {
        extension: 'handlebars' // <---- HERE
      }
```
In this way the package is still able to find the emails folder also in the serverless application.

**Comment by niftylettuce** [comment] 2018-05-20 18:09
@Dinuz see <https://github.com/niftylettuce/email-templates/commit/12ac8b22a38b45ce592bb17d07e131b78c1cd2ea> and the updated README

**Comment by Dinuz** [comment] 2018-05-20 23:18
You rock!!!!

**Comment by niftylettuce** [comment] 2018-05-22 14:39
@ibc the root of your project does not have `package.json`?  why?

`/Users/me/tmp/emails-stuff/package.json` does not exist?

**Comment by ibc** [comment] 2018-05-22 14:39
IMHO there is no need to mimic old behavior when they were wrong and when a new major version is a being released.

Said that, I cannot now make it work (version 4.0.0) even by using the default folder struct (`ROOT/emails/templateName` and `ROO/app.js`). The `root` identified by the lib is `/Users/me/tmp/emails-stuff/node_modules/email-templates` which obvioulsy makes no sense.

**Comment by niftylettuce** [comment] 2018-05-22 14:43
oh this is a definite bug, sorry about that.

@ibc the way it should have worked is fetching root of project

i'll revert to old behavior for now, sec

**Comment by niftylettuce** [comment] 2018-05-22 14:46
v4.0.1 published and I deprecated 4.0.0, sorry about that @ibc

**Comment by Dinuz** [comment] 2018-05-22 14:47
@ibc I am not clear at which version are you referring with current behavior, the 4.0?
If you used my hack and you had the issue, I do assume the problem is way deeper than what I found. My hack just bring you back to version 3.6 behavior; meaning your issue was present also in that release.

@niftylettuce what are your thoughts?

**Comment by niftylettuce** [comment] 2018-05-22 15:11
just to confirm, @Dinuz you are correct 3.6.1 = 4.0.

**Comment by ibc** [comment] 2018-05-22 15:28
Sorry, the latter was my fault. I was setting `views` object in `email.send()` rather than in the `Email` constructor.

**Comment by niftylettuce** [comment] 2018-05-22 15:30
No problem, let me know if you have any more issues with this package (or others).

Just released https://lipo.io btw!

**Comment by ibc** [comment] 2018-05-22 15:32
Thanks. Just a question please:

So for now I'm using 3.6.1 and should upgrade to 4.0.1 (or newer) once the NPM problem is fixed, right?

**Comment by niftylettuce** [comment] 2018-05-22 15:35
@ibc you can stay on 3.6.1 for now, no worries.  I will comment here again and ping you if we release something in 4.x that is breaking or new/improved.

**Comment by ibc** [comment] 2018-05-22 15:39
Thanks a lot.
