### ISSUE TITLE
instance of Email is not reusable

### ISSUE THREAD

**Issue by zdila** [niftylettuce/email-templates#253] opened 2017-10-17 11:10 UTC
We have single instance of `Email` object with some defaults.

```javascript
const email = new Email({
  message: {
    from: {
      name: 'Company',
      address: 'noreply@example.com',
    },
  },
  transport: transporter,
  views: {
    options: {
      extension: 'ejs',
    },
  },
  htmlToText: false,
  juice: true,
  juiceResources: {
    preserveImportant: true,
    webResources: {
      images: false,
    },
  },
});
```

Then we reuse the instance multiple times:

```javascript
await email.send({
  message: {
    to: {
      address: recipient,
    },
  },
  template: `../emailTemplates/${templateName}`,
  locals: context,
});
```

First email sent is OK. All following calls to `email.send` sends email to the same email address as was in the first email.

Problem is that `defaultsDeep` mutates first argument. It affects `message` and `locals`.

**Comment by niftylettuce** [comment] 2017-10-17 18:17
This is a duplicate of #252 and I will have this fixed today.  When I release a new version to NPM I will ping you.  Also feel free to join our Slack at <http://slack.crocodilejs.com/>.

**Closed** 2017-10-17 18:40 UTC

**Comment by niftylettuce** [comment] 2017-10-17 18:41
Please install v3.0.9 from NPM.  `npm install email-templates@latest` or `yarn add email-templates@latest` - this issue is fixed and tests have been written as well to ensure.  Any further issues please open a new issue, and thanks again for reporting.

**Comment by zdila** [comment] 2017-10-18 08:30
It works, thanks!
